# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.6.1
      with:
      # Buildx version. Example: v0.3.0
        buildx-version: latest
    
    - name: Docker Build
      run: |
        docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        cd $GITHUB_WORKSPACE/roborts
        docker buildx build -t kevinlad/roborts:base-slam-rplidar-multiplatform --platform linux/arm64,linux/amd64 . --push
        
        
        

      
        
